version: '3'

services:
  attus-compose-postgres:
    image: postgres:16
    container_name: attus-compose-postgres
    ports:
      - "5433:5432"
    env_file:
      ./docker/.env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - attus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d attus -h localhost -p 5432"]
      interval: 30s
      timeout: 30s
      retries: 3
  attus-spring-boot:
    image: lcsmachaado/attus-processo-seletivo:latest
    container_name: attus-spring-boot
    ports:
      - "8080:8080"
    depends_on:
      - attus-compose-postgres
    networks:
      - attus-network
networks:
  attus-network:
    driver: bridge
volumes:
  database:
    driver: local
